# site settings

title: Sheen Patel
description: Sheen Patel | Portfolio
taglong: Civil Engineering Student at UofT
tagshort: Civil BASc at UofT
url: https://pseudonymPatel.github.io/portfolioWebsite
baseurl: "https://pseudonymPatel.github.io/portfolioWebsite"
permalink: pretty
repo: https://github.com/PseudonymPatel/portfolioWebsite

# author settings

author:
  name: Sheen Patel
  email: sheennpatel@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: username
  github: PseudonymPatel
  instagram: username
  linkedin: sheen-patel
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
